#!/bin/bash
export LC_NUMERIC="en_US.UTF-8"
script_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$script_dir" || exit 1
alifol="../img/output/alp_p3_emi/"
kaifol="../img/output/kap_p3_emi/"
compile_requested=false
range_override=""
rap_override=""

show_help() {
    echo "Usage: bash $0 [-c] [-h] [-r new_omemi:new_omema] [-rho radius ratio]"
    echo ""
    echo "Options:"
    echo "  -c    --compile       Compile the codes before executing the script"
    echo "  -h    --help          Show this help message and exit"
    echo "  -r    --range         Specify new_omemi and new_omema manually in the format new_omemi:new_omema"
    echo "  -rho  --radius-ratio  Set the radius ratio (rap) used in calculations"
    echo ""
    echo "Arguments:"
    echo "  radius  of the particle (default: 10)"
}

while [ $# -gt 0 ]; do
    case "$1" in
        -c|--compile)
            compile_requested=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -r|--range)
            if [ -z "${2:-}" ]; then
                echo "Error: -r|--range requires an argument in the form omemi:omema" >&2
                exit 1
            fi
            range_override="$2"
            shift 2
            ;;
        -rho|--radius-ratio)
            if [ -z "${2:-}" ]; then
                echo "Error: -rho|--radius-ratio requires a value" >&2
                exit 1
            fi
            rap_override="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1" >&2
            show_help
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [ -n "$range_override" ] && [[ "$range_override" != *:* ]]; then
    echo "Error: -r|--range requires omemi:omema" >&2
    exit 1
fi

bin_targets=(../bin/fro ../bin/oGp ../bin/oap)
src_targets=(../src/frohlich.cxx ../src/nanoshell_ome_al_p3.cxx ../src/nanoshell_omeG_p3.cxx)
gp_scripts=(emi_maps.gp emi_wh.gp emi_maps_step.gp)
missing=()
missing_exec=false

if [ "$compile_requested" = true ]; then
    for src in "${src_targets[@]}"; do
        [ -f "$src" ] || missing+=("$src (source)")
    done
else
    for bin in "${bin_targets[@]}"; do
        if [ ! -x "$bin" ]; then
            missing_exec=true
            missing+=("$bin (executable)")
        fi
    done
fi

for gp in "${gp_scripts[@]}"; do
    [ -f "$gp" ] || missing+=("$gp (gnuplot)")
done

if [ ${#missing[@]} -gt 0 ]; then
    if [ "$compile_requested" = true ]; then
        echo "> Compilation requested but the following files are missing:"
    else
        echo "> Missing required files:"
    fi
    for item in "${missing[@]}"; do
        echo "  - $item"
    done
    if [ "$compile_requested" != true ] && [ "$missing_exec" = true ]; then
        echo "> Hint: rerun with the -c flag to rebuild the executables."
    fi
    exit 1
fi

if [ "$compile_requested" = true ]; then
    echo
    echo "> Compiling codes..."
    g++ -Wall -I/usr/local/include -L/usr/local/lib ../src/frohlich.cxx -o ../bin/fro -lgsl -lgslcblas -lm -larmadillo
    g++ -Wall -I/usr/include/ -L/usr/local/lib ../src/nanoshell_ome_al_p3.cxx -o ../bin/oap -lgsl -lgslcblas -lm -larmadillo
    g++ -Wall -I/usr/include/ -L/usr/local/lib ../src/nanoshell_omeG_p3.cxx -o ../bin/oGp -lgsl -lgslcblas -lm -larmadillo
    echo "> ...Done!"
    echo
fi
none=1.e-30

read  a  Dome  ome21  G  omemi  omema  metal  model  gain_model  solvent E0 rap host < ../data/input/nanosphere_eV.dat
rap_tmp=$rap

if [ $model == "spline" ]; then
    echo "Error: Current system is buggy with interpolated metal permittivity."
    echo "Change model to drudein data/input/nanosphere_eV.dat!"
    exit 1
fi

if [ -n "$range_override" ]; then
    IFS=: read -r omi oma <<< "$range_override"
    if [ -z "$omi" ] || [ -z "$oma" ]; then
        echo "Error: -r|--range requires omemi:omema" >&2
        exit 1
    fi
    ex1=$(printf '%.6g' "$(echo "$omi - 0.3" | bc -l)")
    ex2=$(printf '%.6g' "$(echo "$oma + 0.3" | bc -l)")
elif [ $metal == "gold" ]; then
    ex1=1.6;
    ex2=2.8;
    omi=1.6;
    oma=2.8;
elif [ $metal == "silver" ]; then
    ex1=2.0;
    ex2=4.5;
    omi=2.2;
    oma=3.4;    
fi

if [ -n "$rap_override" ]; then
    rap_tmp=$rap_override
fi
fro=(`./../bin/fro`)
omeG=${fro[0]}
Gth=${fro[1]}
echo "> Setting the gain at the frohlich frequency"
echo "> and setting the probe field to "$none"..."
{
    echo "$a $Dome $omeG $G $omi $oma $metal $model $gain_model $solvent $none $rap_tmp $host"
    echo "# a Dome omeG G omi oma metal model gain_model solvent none rap_tmp host"
    echo "** WARNING: This file was automatically edited by $0."
    echo "** Do not edit this file manually until the process ends."
} > ../data/input/nanosphere_eV.dat
focurr="rho"$rap_tmp"-"$host"-at-"$metal"-in-"$solvent"/"
echo "> ...Done!"
echo
echo "> the emission threshold is Gth = "$Gth
echo
echo "> Producing HEAT MAPS"
{
    echo "$a $Dome $omeG $G $ex1 $ex2 $metal $model $gain_model $solvent $none $rap_tmp $host"
    echo "# a Dome omeG G ex1 ex2 metal model gain_model solvent none rap_tmp host"
    echo "** WARNING: This file was automatically edited by $0."
    echo "** Do not edit this file manually until the process ends."
} > ../data/input/nanosphere_eV.dat
./../bin/oGp
{
    echo "$a $Dome $omeG $G $omi $oma $metal $model $gain_model $solvent $none $rap_tmp $host"
    echo "# a Dome omeG G omi oma metal model gain_model solvent none rap_tmp host"
    echo "** WARNING: This file was automatically edited by $0."
    echo "** Do not edit this file manually until the process ends."
} > ../data/input/nanosphere_eV.dat
ogpfol="../img/output/oGp/"
mnewdir=$ogpfol$focurr
echo "> Removing old files from the image folder: "$ogpfol
rm -fr $mnewdir
echo "> ...Done!"
echo "> Creating image folder: "$mnewdir
mkdir -p $mnewdir
gnuplot emi_maps.gp
mv $ogpfol*.png $mnewdir

echo
echo
echo " Producing SPECTRA"
echo
anewdir=$alifol$focurr
knewdir=$kaifol$focurr
echo "> Removing old files from the image folder: "$alifol
rm -fr $anewdir
echo "> Removing old files from the image folder: "$kaifol
rm -fr $knewdir
echo "> ...Done!"
echo "> Creating image folder: "$anewdir
mkdir -p $anewdir
echo "> Creating image folder: "$knewdir
mkdir -p $knewdir
echo "> Creating image folders: map_isa and map_isk"
mkdir -p $mnewdir"map_isa"
mkdir -p $mnewdir"map_isk"
echo "> ...Done!"
echo 
focurr="rho"$rap_tmp"-"$host"-at-"$metal"-in-"$solvent"/"
echo "> Removing old files from the image folder: GIF"
gifdir="../img/output/GIF/"$focurr
rm -fr $gifdir
echo "> Creating image folders: GIF/"$focurr
echo $gifdir
mkdir -p $gifdir
mkdir -p $gifdir"kappa/"
mkdir -p $gifdir"alpha/"
for ii in {0..20..1}; do
    iG=`echo $ii*0.1|bc -l`
    iG=`printf '%.3f\n' $iG`
    iname=`printf "%03d" $ii`
    mG=`echo $iG*$Gth|bc -l`
    echo -e "   > Calculating the emission spectrum for G = "$iG"*Gth\t=\t"$mG
    {
        echo "$a $Dome $omeG $mG $ex1 $ex2 $metal $model $gain_model $solvent $E0 $rap_tmp $host"
        echo "# a Dome omeG mG ex1 ex2 metal model gain_model solvent E0 rap_tmp host"
        echo "** WARNING: This file was automatically edited by $0."
        echo "** Do not edit this file manually until the process ends."
    } > ../data/input/nanosphere_eV.dat
    ./../bin/oap
    {
        echo "$a $Dome $omeG $mG $omi $oma $metal $model $gain_model $solvent $E0 $rap_tmp $host"
        echo "# a Dome omeG mG omi oma metal model gain_model solvent E0 rap_tmp host"
        echo "** WARNING: This file was automatically edited by $0."
        echo "** Do not edit this file manually until the process ends."
    } > ../data/input/nanosphere_eV.dat
    gnuplot emi_wh.gp
    mv "../img/output/emi_wh.pdf" $anewdir"/emi_"$iG"Gth.pdf"
    convert -density 300 $anewdir"/emi_"$iG"Gth.pdf" $anewdir"/emi_"$iname".png"
    rm $anewdir"/emi_"$iG"Gth.pdf"
    mv "../img/output/kmi_wh.pdf" $knewdir"/emi_"$iG"Gth.pdf"
    convert -density 300 $knewdir"/emi_"$iG"Gth.pdf" $knewdir"/emi_"$iname".png"
    rm $knewdir"/emi_"$iG"Gth.pdf"
    gnuplot -c emi_maps_step.gp $mG
    mv $ogpfol"map_isa_step.png" $mnewdir"map_isa/emi_"$iname".png"
    mv $ogpfol"map_isk_step.png" $mnewdir"map_isk/emi_"$iname".png"
    convert -resize x940 $anewdir"/emi_"$iname".png" "../img/output/temp0.png"
    convert -resize x940 $mnewdir"map_isa/emi_"$iname".png" "../img/output/temp1.png"
    convert +append "../img/output/temp0.png" "../img/output/temp1.png" $gifdir"alpha/emi_"$iname".png"
    convert -resize x940 $knewdir"/emi_"$iname".png" "../img/output/temp0.png"
    convert -resize x940 $mnewdir"map_isk/emi_"$iname".png" "../img/output/temp1.png"
    convert +append "../img/output/temp0.png" "../img/output/temp1.png" $gifdir"kappa/emi_"$iname".png"
    rm "../img/output/temp0.png" 
    rm "../img/output/temp1.png"
done
convert -delay 20 -loop 0 -dispose previous $gifdir"alpha/*.png"  $gifdir"alpha.gif"
convert -delay 20 -loop 0 -dispose previous $gifdir"kappa/*.png"  $gifdir"kappa.gif"
echo "> Resetting the original input file..."
{
    echo "$a $Dome $ome21 $G $omemi $omema $metal $model $gain_model $solvent $E0 $rap $host"
    echo "# a Dome ome21 G omemi omema metal model gain_model solvent E0 rap host"
} > ../data/input/nanosphere_eV.dat
echo "> ...Done!"
