#!/bin/bash
CXXFLAGS="${CXXFLAGS:-} -I../include"
# scripts/GxN.bash
#
# Gain × Frequency numerical runs using nanoshell_num (nsn)
# Thresholds obtained from frohlich.cxx

export LC_NUMERIC="en_US.UTF-8"

show_help() {
  echo "Usage: bash $0 [-c] [-h]"
  echo ""
  echo "Options:"
  echo "  -c    Compile frohlich.cxx and nanoshell_num.cxx before running"
  echo "  -h    Show this help message and exit"
}

use_compile=false
while getopts "ch" opt; do
  case ${opt} in
    c ) use_compile=true ;;
    h ) show_help; exit 0 ;;
    * ) show_help; exit 1 ;;
  esac
done

infile="../data/input/nanosphere_eV.dat"
outbase="../data/output/GxN"

if [ ! -f "$infile" ]; then
  echo "Error: Input file '$infile' not found."
  exit 1
fi

if $use_compile; then
  echo "> Compiling frohlich and nanoshell_num..."
  g++ $CXXFLAGS -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib \
      ../src/frohlich.cxx -o ../bin/fro \
      -lgsl -lgslcblas -lm -larmadillo

  g++ $CXXFLAGS -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib \
      ../src/nanoshell_num.cxx -o ../bin/nsn \
      -lgsl -lgslcblas -lm -larmadillo
fi

if [ ! -x "../bin/fro" ]; then
  echo "Error: ../bin/fro not found or not executable."
  exit 1
fi

if [ ! -x "../bin/nsn" ]; then
  echo "Error: ../bin/nsn not found or not executable."
  exit 1
fi

mkdir -p "$outbase"

# Backup input
cp "$infile" "${infile}.bak" || exit 1

# Read first line (same pattern as intime.bash)
read a Dome ome_g G omemi omema mtl mdl active sol E0 rho hst < "$infile"

# Frohlich thresholds
info=$(../bin/fro)
ometh=$(echo "$info" | awk '{print $1}')
Gth=$(echo "$info"   | awk '{print $2}')

if [ -z "$ometh" ] || [ -z "$Gth" ]; then
  echo "Error: failed to parse frohlich output."
  mv "${infile}.bak" "$infile"
  exit 1
fi

echo "> Frohlich: ometh = $ometh   Gth = $Gth"
echo "$ometh $Gth" > ../data/output/frohlich.dat

write_input() {
  local newG="$1"
  {
    echo "$a $Dome $ometh $newG $omemi $omema $mtl $mdl $active $sol $E0 $rho $hst"
    echo "# a Dome ome_g G omemi omema mtl mdl atv sol E0 rho host"
    echo "** WARNING: automatically modified by GxN.bash"
  } > "$infile"
}

echo ""
run_case() {
  local tag="$1"
  local ome="$2"
  local gmult="$3"

  local Gval
  Gval=$(echo "$gmult * $Gth" | bc -l)

  echo "> $tag : ome = $ome   G = $Gval"

  write_input "$Gval"

  mkdir -p "$outbase/$tag"

  ../bin/nsn "$ome"

  for f in numtime.dat numfunc.dat; do
    if [ -f "../data/output/$f" ]; then
      mv "../data/output/$f" "$outbase/$tag/"
    else
      echo "Warning: $f not produced in this run."
    fi
  done

  {
    echo "ometh = $ometh"
    echo "Gth   = $Gth"
    echo "ome   = $ome"
    echo "G     = $Gval"
  } > "$outbase/$tag/README.txt"
}

ome1="$ometh"
ome2=$(echo "1.1 * $ometh" | bc -l)

run_case "G1p1_ometh"      "$ome1" "1.1"
run_case "G1p5_ometh"      "$ome1" "1.5"
run_case "G1p1_1p1ometh"   "$ome2" "1.1"
run_case "G1p5_1p1ometh"   "$ome2" "1.5"

# Restore input
mv "${infile}.bak" "$infile"

echo ""
echo "> All runs completed. Results in $outbase/"

# -----------------------------
# Generate gnuplot script (2 panels)
# -----------------------------
gpfile="../scripts/GxN_time.gp"
pngout="../img/output/GxN_time.png"

G11=$(echo "1.1 * $Gth" | bc -l)
G15=$(echo "1.5 * $Gth" | bc -l)

f_om_G11="$outbase/G1p1_ometh/numtime.dat"
f_om_G15="$outbase/G1p5_ometh/numtime.dat"
f_11_G11="$outbase/G1p1_1p1ometh/numtime.dat"
f_11_G15="$outbase/G1p5_1p1ometh/numtime.dat"

cat > "$gpfile" << EOF
# Auto-generated by GxN.bash
# Two-panel plot: top = ometh runs, bottom = 1.1*ometh runs
# Convention: N*G = (col6)*G -> asymptote is ~N*Gth and we set ~N = 1, so y -> Gth

set term pngcairo enhanced size 1200,900
set output "${pngout}"

# Embedded values from bash
Gth   = ${Gth}
G11   = ${G11}
G15   = ${G15}
ometh = ${ometh}

set grid
set key outside
set tics out
set border lw 1

set multiplot layout 2,1 title "GxN(t) →  ÑxGth"

# ---------------- Top panel: omega = ometh ----------------
set title sprintf("{/Symbol w} = {/Symbol w}_{th} = %.6g eV", ometh)
set xlabel ""
set ylabel "N(t)xG"

unset arrow
unset label

set arrow 1 nohead from graph 0, first Gth to graph 1, first Gth filled dt 2 lw 2
set label 1 sprintf("ÑxGth = %.6g", Gth) at graph 0.98, first Gth right offset 0,-0.7

plot \
  "${f_om_G11}" u (\$1):(\$6*G11) w l lw 2 title "G = 1.1 Gth", \
  "${f_om_G15}" u (\$1):(\$6*G15) w l lw 2 title "G = 1.5 Gth"

# ---------------- Bottom panel: omega = 1.1*ometh ----------------
set title sprintf("{/Symbol w} = 1.1x{/Symbol w}_{th} = %.6g eV", 1.1*ometh)
set xlabel "t (ps)"
set ylabel "N(t)xG"

plot \
  "${f_11_G11}" u (\$1):(\$6*G11) w l lw 2 title "G = 1.1 Gth", \
  "${f_11_G15}" u (\$1):(\$6*G15) w l lw 2 title "G = 1.5 Gth"

unset multiplot
set output
EOF

echo ""
echo "> Wrote gnuplot script: $gpfile"
echo "> Target figure:       $pngout"

if command -v gnuplot >/dev/null 2>&1; then
  gnuplot "$gpfile"
  echo "> Rendered: $pngout"
else
  echo "Warning: gnuplot not found; run manually: gnuplot $gpfile"
fi

exit 0
