#!/bin/bash
# pulling.bash
# Generate the steady-state intensity and fixed-gain p3 spectrum at G = 1.2 Gth.

set -euo pipefail
export LC_NUMERIC="en_US.UTF-8"

script_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$script_dir" || exit 1

CXX=g++
NGM_ROOT="$(realpath ../extern/nano_geo_matrix)"
CXXFLAGS="-Wall -I$NGM_ROOT/include -I$NGM_ROOT/modules -I$NGM_ROOT/modules/cup -I/usr/local/include -I/usr/include/eigen3"
LDFLAGS="-L/usr/local/lib"
LIBS="-lgsl -lgslcblas -lm -larmadillo"

compile_requested=false
out_dir="../data/output/pulling"

show_help() {
    echo "Usage: bash $0 [-c] [-h] [-o output_dir]"
    echo ""
    echo "Options:"
    echo "  -c, --compile   Compile required executables before running"
    echo "  -h, --help      Show this help message and exit"
    echo "  -o, --output    Output directory, default: $out_dir"
}

while [ $# -gt 0 ]; do
    case "$1" in
        -c|--compile)
            compile_requested=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -o|--output)
            if [ -z "${2:-}" ]; then
                echo "Error: -o|--output requires a directory path" >&2
                exit 1
            fi
            out_dir="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1" >&2
            show_help
            exit 1
            ;;
        *)
            echo "Unexpected argument: $1" >&2
            show_help
            exit 1
            ;;
    esac
done

bin_targets=(../bin/fro ../bin/nsISS ../bin/oap)
src_targets=(../src/frohlich.cxx ../src/nanoshell_ISS.cxx ../src/nanoshell_ome_al_p3.cxx)

missing=()
missing_exec=false

if [ "$compile_requested" = true ]; then
    for src in "${src_targets[@]}"; do
        [ -f "$src" ] || missing+=("$src (source)")
    done
else
    for bin in "${bin_targets[@]}"; do
        if [ ! -x "$bin" ]; then
            missing_exec=true
            missing+=("$bin (executable)")
        fi
    done
fi

if [ ${#missing[@]} -gt 0 ]; then
    if [ "$compile_requested" = true ]; then
        echo "> Compilation requested but the following files are missing:"
    else
        echo "> Missing required files:"
    fi
    for item in "${missing[@]}"; do
        echo "  - $item"
    done
    if [ "$compile_requested" != true ] && [ "$missing_exec" = true ]; then
        echo "> Hint: rerun with -c to rebuild the executables."
    fi
    exit 1
fi

if [ "$compile_requested" != true ]; then
    if [ "../src/frohlich.cxx" -nt "../bin/fro" ] ||
       [ "../src/nanoshell_ISS.cxx" -nt "../bin/nsISS" ] ||
       [ "../src/nanoshell_ome_al_p3.cxx" -nt "../bin/oap" ]; then
        echo "> Source is newer than an executable; recompiling."
        compile_requested=true
    fi
fi

if [ "$compile_requested" = true ]; then
    echo
    echo "> Compiling codes..."
    $CXX $CXXFLAGS ../src/frohlich.cxx -o ../bin/fro $LDFLAGS $LIBS
    $CXX $CXXFLAGS ../src/nanoshell_ISS.cxx -o ../bin/nsISS $LDFLAGS $LIBS
    $CXX $CXXFLAGS ../src/nanoshell_ome_al_p3.cxx -o ../bin/oap $LDFLAGS $LIBS
    echo "> ...Done!"
    echo
fi

input_file="../data/input/nanosphere_eV.dat"
[ -f "$input_file" ] || { echo "Error: input file not found: $input_file" >&2; exit 1; }

mkdir -p "$out_dir" "../data/output/oGp"

input_backup="$(mktemp)"
cp -f "$input_file" "$input_backup"
cleanup() {
    mv -f "$input_backup" "$input_file" >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM

read -r a Dome ome_g G omemi omema metal model gain_model solvent E0 rho host < "$input_file"

fro_raw="$("../bin/fro")"
read -r omega_th Gth < <(awk '
    {
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^-?([0-9]+([.][0-9]*)?|[.][0-9]+)([eE][-+]?[0-9]+)?$/) {
                n++
                value[n] = $i
                if (n == 2) {
                    print value[1], value[2]
                    exit
                }
            }
        }
    }
    END { if (n < 2) exit 1 }
' <<< "$fro_raw")

if [ -z "${omega_th:-}" ] || [ -z "${Gth:-}" ]; then
    echo "Error: frohlich calculation did not provide omega_th and Gth." >&2
    echo "Raw output was:" >&2
    echo "$fro_raw" >&2
    exit 1
fi

gain="$(awk -v gth="$Gth" 'BEGIN { printf "%.12g", 1.2*gth }')"

echo "> Frohlich frequency omega_th = $omega_th eV"
echo "> Threshold gain Gth = $Gth"
echo "> Setting gain to 1.2*Gth = $gain"

{
    echo "$a $Dome $omega_th $gain $omemi $omema $metal $model $gain_model $solvent $E0 $rho $host"
    echo "# a Dome omega_th G omemi omema metal model gain_model solvent E0 rho host"
    echo "** WARNING: This file was automatically edited by $0."
    echo "** Do not edit this file manually until the process ends."
} > "$input_file"

echo "> Running nsISS..."
"../bin/nsISS" > "$out_dir/nsISS.log" 2>&1
[ -f "../data/output/ns_intensity_SS.dat" ] || {
    echo "Error: missing ../data/output/ns_intensity_SS.dat after nsISS" >&2
    exit 1
}
cp -f "../data/output/ns_intensity_SS.dat" "$out_dir/ns_intensity_SS.dat"

echo "> Running oap..."
"../bin/oap" > "$out_dir/oap.log" 2>&1
[ -f "../data/output/oGp/ome_p3.dat" ] || {
    echo "Error: missing ../data/output/oGp/ome_p3.dat after oap" >&2
    exit 1
}
cp -f "../data/output/oGp/ome_p3.dat" "$out_dir/ome_p3.dat"

{
    echo "# pulling.bash metadata"
    echo "omega_th $omega_th"
    echo "Gth $Gth"
    echo "G 1.2*Gth $gain"
} > "$out_dir/pulling.info"

echo "> Wrote $out_dir/ns_intensity_SS.dat"
echo "> Wrote $out_dir/ome_p3.dat"
echo "> Wrote $out_dir/pulling.info"
echo "> Done. Original input restored automatically."
