#!/bin/bash
CXXFLAGS="${CXXFLAGS:-} -I../include"
export LC_NUMERIC="en_US.UTF-8"
script_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$script_dir" || exit 1

compile_requested=false
e0_range_override=""

show_help() {
    echo "Usage: bash $0 [-c] [-h] [-e0r \"8 9 10 11\"]"
    echo ""
    echo "Options:"
    echo "  -c    --compile  Compile the codes before executing the script"
    echo "  -h    --help     Show this help message and exit"
    echo "  -e0r  --e0-range Space-separated, increasing positive integers for E0 exponents (default: 8 9 10 11)"
}

while [ $# -gt 0 ]; do
    case "$1" in
        -c|--compile)
            compile_requested=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -e0r|--e0-range)
            if [ -z "${2:-}" ]; then
                echo "Error: -e0r|--e0-range requires a space-separated list of positive integers" >&2
                exit 1
            fi
            e0_range_override="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1" >&2
            show_help
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

bin_targets=(../bin/fro ../bin/nsh)
src_targets=(../src/frohlich.cxx ../src/nanoshell_num_anl.cxx)
missing=()

if [ "$compile_requested" = true ]; then
    for src in "${src_targets[@]}"; do
        [ -f "$src" ] || missing+=("$src (source)")
    done
else
    for bin in "${bin_targets[@]}"; do
        [ -x "$bin" ] || missing+=("$bin (executable)")
    done
fi

if [ ${#missing[@]} -gt 0 ]; then
    if [ "$compile_requested" = true ]; then
        echo "> Compilation requested but the following files are missing:"
    else
        echo "> Missing required files:"
        echo "> Hint: rerun with the -c flag to rebuild the executables."
    fi
    for item in "${missing[@]}"; do
        echo "  - $item"
    done
    exit 1
fi

if [ "$compile_requested" = true ]; then
    echo "> Compiling codes..."
    g++ $CXXFLAGS -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib ../src/frohlich.cxx -o ../bin/fro -lgsl -lgslcblas -lm -larmadillo
    g++ $CXXFLAGS -Wall -I/usr/include/ -I/usr/include/eigen3 -L/usr/local/lib ../src/nanoshell_num_anl.cxx -o ../bin/nsh -lgsl -lgslcblas -lm -larmadillo
    echo "> ...done compiling!"
fi

file_path="../data/input/nanosphere_eV.dat"
echo "> WARNING: $file_path will be temporarily overwritten during the calculations."

read r Dome ome_g G omemi omema mtl mdl atv hst E0 rho sol < <(grep -v '^#' "$file_path")

# Backup the original file
cp "$file_path" "${file_path}.bak"

fro_output=($(./../bin/fro))
ome_sp=${fro_output[0]}
new_G=$(echo "1.01*${fro_output[1]}" | bc -l)

if [ -n "$e0_range_override" ]; then
    read -r -a e0_values <<< "$e0_range_override"
else
    e0_values=(8 9 10 11)
fi

if [ ${#e0_values[@]} -eq 0 ]; then
    echo "Error: -e0r|--e0-range requires at least one value" >&2
    exit 1
fi

prev_val=0
for val in "${e0_values[@]}"; do
    if ! [[ "$val" =~ ^[0-9]+$ ]]; then
        echo "Error: -e0r|--e0-range values must be positive integers" >&2
        exit 1
    fi
    if [ "$val" -le 0 ]; then
        echo "Error: -e0r|--e0-range values must be positive integers" >&2
        exit 1
    fi
    if [ "$val" -le "$prev_val" ]; then
        echo "Error: -e0r|--e0-range values must be strictly increasing" >&2
        exit 1
    fi
    prev_val=$val
done

echo "> Calculating for different E0..."
for i in "${e0_values[@]}"; do 
    newE0="1.e-$i"
    {
        echo "$r $Dome $ome_sp $new_G $omemi $omema $mtl $mdl $atv $hst $newE0 $rho $sol"
        echo "# r Dome ome_sp new_G omemi omema mtl mdl atv hst newE0 rho sol"
        echo "** WARNING: This file was automatically edited by $0."
        echo "** Do not edit this file manually until the process ends."
    } > "$file_path"
    ./../bin/nsh 2.811 # $ome_sp
    cp "../data/output/numtime.dat" "../data/output/numtime$(printf "%02d" $i).dat"
done
echo "> ...done!"

# Reinstate the original content of the file
echo "> Reinstating the original content of $file_path"
{
  echo "$r $Dome $ome_g $G $omemi $omema $mtl $mdl $atv $hst $E0 $rho $sol"
  echo "# r Dome ome_g G omemi omema mtl mdl atv hst E0 rho sol"
} > "$file_path"
echo "> done!"
